import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import * as motion from "motion/react-client"

const jakarta = Plus_Jakarta_Sans({})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"      
    >
      <body className={`${jakarta.style} bg-orange-50`}>{children}</body>
    </html>
  );
}
